//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int a_id { get; set; }
        public int p_id { get; set; }
        public int d_id { get; set; }
        public System.DateTime date { get; set; }
        public string status { get; set; }
        public string a_fname { get; set; }
        public string a_lname { get; set; }
        public string a_gender { get; set; }
        public string a_email { get; set; }
        public int a_contact { get; set; }
    }
}
