//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int d_id { get; set; }
        public string d_name { get; set; }
        public string d_email { get; set; }
        public string d_address { get; set; }
        public string d_dept { get; set; }
        public Nullable<int> d_salary { get; set; }
        public string d_experience { get; set; }
        public int d_contact { get; set; }
        public string d_image { get; set; }
        public string d_qualification { get; set; }
        public string d_wh { get; set; }
    }
}
