//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;

    public partial class FDoctor
    {
        public int df_id { get; set; }
        public string df_name { get; set; }
        public string df_phone { get; set; }
        public string df_address { get; set; }
        public string df_spe { get; set; }
        public string df_image { get; set; }
        public HttpPostedFileBase DfImage { get; set; }
        public string df_resume { get; set; }
        public HttpPostedFileBase DfPdf { get; set; }
        public int df_experience { get; set; }
        public string df_password { get; set; }
        public Nullable<int> df_salary { get; set; }
        public string df_email { get; set; }
    }
}