//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int p_id { get; set; }
        public string p_firstname { get; set; }
        public string p_lastname { get; set; }
        public string p_email { get; set; }
        public string p_password { get; set; }
    }
}
